server:
  port: 8200
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.112.78:3306/lg?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: travel
    password: 123456
  redis:
    host: 162.14.112.78
    port: 6379
    password: 123
    database: 2
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: lg-comment-8200 # 注册到注册中心的名字
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.group8.entity
  #下划线转驼峰配置
  configuration:
    map-underscore-to-camel-case: true
