server:
  port: 8101

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.112.78:3306/lg?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: travel
    password: 123456
  application:
    name: lg-eamil-8101 # 注册到注册中心的名字
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest

mybatis:
  type-aliases-package: com.group.entity
  mapper-locations: classpath:/dao/*.xml

mail:
  subject: 来自飞鸽旅社的通知
  content: 欢迎{username},您的验证码w为{code},请在5分钟内激活~


