server:
  port: 8100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.112.78:3306/lg?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: travel
    password: 123456
  application:
    name: lg-user-8100 # 注册到注册中心的名字
  # 分页插件允许循环依赖
  main:
    allow-circular-references: true
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest

mybatis:
  type-aliases-package: com.group8.entity
  mapper-locations: classpath:/dao/*.xml
  #下划线转驼峰配置
  configuration:
    map-underscore-to-camel-case: true

#日志配置
logging:
  level:
    com.group8.dao: debug
