server:
  port: 8100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.112.78:3306/lg?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: travel
    password: 123456
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: lg-user-8100 # 注册到注册中心的名字
  main:
    # 允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true
    # 分页插件允许循环依赖
    allow-circular-references: true
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest

  #redis配置
  redis:
    host: 162.14.112.78
    password: 123
    database: 1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 5
        min-idle: 0
        max-wait: -1ms

mybatis:
  type-aliases-package: com.group8.entity
  mapper-locations: classpath:/dao/*.xml
  #下划线转驼峰配置
  configuration:
    map-underscore-to-camel-case: true

#日志配置
logging:
  level:
    com.group8.dao: debug
